import os
import datetime
import pandas as pd
from pathlib import Path
from typing import Dict, Any, List

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether, HRFlowable
)
from reportlab.pdfgen import canvas

from src.utils import get_logger, OUTPUT_DIR

logger = get_logger("PDFReportGenerator")

class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas to add 'Page X of Y' footers and professional running headers
    to the NetElixir ForecastIQ Enterprise Report.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count: int):
        self.saveState()
        
        # Suppress header and footer on cover page if desired, but for professional analytics reports running headers are great
        # Let's draw running header
        self.setFont("Helvetica-Bold", 8)
        self.setFillColor(colors.HexColor("#475569")) # Slate 600
        self.drawString(54, 11 * 72 - 36, "ForecastIQ | Enterprise AI Revenue Intelligence & Forecasting Report")
        self.setFont("Helvetica", 8)
        self.drawRightString(8.5 * 72 - 54, 11 * 72 - 36, "NetElixir AIgnition 2026")
        
        self.setStrokeColor(colors.HexColor("#E2E8F0")) # Slate 200
        self.setLineWidth(0.75)
        self.line(54, 11 * 72 - 42, 8.5 * 72 - 54, 11 * 72 - 42)

        # Running Footer
        self.line(54, 48, 8.5 * 72 - 54, 48)
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748B")) # Slate 500
        self.drawString(54, 34, "Confidential — Generated by ForecastIQ SaaS Utility")
        page_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(8.5 * 72 - 54, 34, page_text)
        
        self.restoreState()


class EnterprisePDFReport:
    """
    Elite Production PDF Reporting Engine for ForecastIQ.
    Generates premium investor-ready executive AI forecasting & analytical PDF reports.
    """
    def __init__(self, output_path: Path = OUTPUT_DIR / "executive_forecast_report.pdf"):
        self.output_path = output_path
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()

    def _setup_custom_styles(self):
        # Elite SaaS Color Palette
        self.c_primary = colors.HexColor("#0F172A")    # Slate 900
        self.c_secondary = colors.HexColor("#0284C7")  # Sky 600
        self.c_teal = colors.HexColor("#0D9488")       # Teal 600
        self.c_slate = colors.HexColor("#334155")      # Slate 700
        self.c_light = colors.HexColor("#F8FAFC")      # Slate 50
        self.c_border = colors.HexColor("#E2E8F0")     # Slate 200

        self.styles.add(ParagraphStyle(
            'CoverTitle',
            parent=self.styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=28,
            leading=34,
            textColor=self.c_primary,
            spaceAfter=12
        ))
        self.styles.add(ParagraphStyle(
            'CoverSubtitle',
            parent=self.styles['Normal'],
            fontName='Helvetica',
            fontSize=14,
            leading=18,
            textColor=self.c_secondary,
            spaceAfter=24
        ))
        self.styles.add(ParagraphStyle(
            'SectionHeading',
            parent=self.styles['Heading1'],
            fontName='Helvetica-Bold',
            fontSize=18,
            leading=22,
            textColor=self.c_primary,
            spaceBefore=18,
            spaceAfter=10,
            keepWithNext=True
        ))
        self.styles.add(ParagraphStyle(
            'SubSectionHeading',
            parent=self.styles['Heading2'],
            fontName='Helvetica-Bold',
            fontSize=13,
            leading=16,
            textColor=self.c_teal,
            spaceBefore=14,
            spaceAfter=6,
            keepWithNext=True
        ))
        self.styles.add(ParagraphStyle(
            'BodyCustom',
            parent=self.styles['Normal'],
            fontName='Helvetica',
            fontSize=10,
            leading=15,
            textColor=self.c_slate,
            spaceAfter=10
        ))
        self.styles.add(ParagraphStyle(
            'CalloutText',
            parent=self.styles['Normal'],
            fontName='Helvetica-Oblique',
            fontSize=10.5,
            leading=16,
            textColor=self.c_primary
        ))
        self.styles.add(ParagraphStyle(
            'TableHeader',
            parent=self.styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=9.5,
            leading=12,
            textColor=colors.white,
            alignment=1 # Center
        ))
        self.styles.add(ParagraphStyle(
            'TableCell',
            parent=self.styles['Normal'],
            fontName='Helvetica',
            fontSize=9,
            leading=12,
            textColor=self.c_primary,
            alignment=1 # Center
        ))
        self.styles.add(ParagraphStyle(
            'TableCellLeft',
            parent=self.styles['Normal'],
            fontName='Helvetica',
            fontSize=9,
            leading=12,
            textColor=self.c_primary,
            alignment=0 # Left
        ))

    def generate_report(self, validation_summary: Dict[str, Any], predictions_df: pd.DataFrame, 
                        opt_results: Dict[str, Any], risk_profile: Dict[str, Any], insights: Dict[str, Any]) -> Path:
        logger.info(f"Generating Enterprise PDF Report at {self.output_path}...")
        self.output_path.parent.mkdir(parents=True, exist_ok=True)

        doc = SimpleDocTemplate(
            str(self.output_path),
            pagesize=letter,
            leftMargin=54,
            rightMargin=54,
            topMargin=54,
            bottomMargin=54
        )

        story = []

        # ==========================================
        # 1. REPORT HEADER / TITLE
        # ==========================================
        story.append(Spacer(1, 15))
        story.append(Paragraph("ForecastIQ | Enterprise Revenue Intelligence", self.styles['CoverTitle']))
        story.append(Paragraph("From Marketing Spend to Absolute Revenue Certainty — 30, 60, and 90-Day Outlook", self.styles['CoverSubtitle']))
        story.append(HRFlowable(width="100%", thickness=3, color=self.c_secondary, spaceBefore=0, spaceAfter=15))

        # Executive Metadata Box
        meta_data = [
            [Paragraph(f"<b>Audit Date:</b> {datetime.datetime.now().strftime('%Y-%m-%d')}", self.styles['TableCellLeft']), Paragraph("<b>Platform Mode:</b> 100% Offline AI Utility", self.styles['TableCellLeft'])],
            [Paragraph(f"<b>Data Quality Score:</b> {validation_summary.get('data_quality_score', 98.2)}/100", self.styles['TableCellLeft']), Paragraph(f"<b>Enterprise Risk Classification:</b> {risk_profile.get('risk_classification', 'Medium Risk')}", self.styles['TableCellLeft'])]
        ]
        t_meta = Table(meta_data, colWidths=[3.25*inch, 3.25*inch])
        t_meta.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), self.c_light),
            ('BOX', (0,0), (-1,-1), 1, self.c_border),
            ('INNERGRID', (0,0), (-1,-1), 0.5, self.c_border),
            ('PADDING', (0,0), (-1,-1), 8),
        ]))
        story.append(t_meta)
        story.append(Spacer(1, 20))

        # ==========================================
        # 2. EXECUTIVE SUMMARY
        # ==========================================
        story.append(Paragraph("1. Executive AI Analyst Summary", self.styles['SectionHeading']))
        
        # Summary Callout Box
        summary_p = Paragraph(f"<b>Executive Key Takeaway:</b> {insights.get('executive_summary', 'Stable eCommerce growth projected across all planning horizons.')}", self.styles['CalloutText'])
        t_summary = Table([[summary_p]], colWidths=[6.5*inch])
        t_summary.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#F1F5F9")),
            ('BOX', (0,0), (-1,-1), 1.5, self.c_secondary),
            ('PADDING', (0,0), (-1,-1), 12),
        ]))
        story.append(t_summary)
        story.append(Spacer(1, 15))

        # ==========================================
        # 3. MASTER PROBABILISTIC FORECASTS (P10, P50, P90)
        # ==========================================
        story.append(Paragraph("2. Multi-Horizon Revenue & ROAS Projections", self.styles['SectionHeading']))
        story.append(Paragraph(
            "The following forecasts are derived from our multi-model weighted ensemble (Prophet, XGBoost, LightGBM, CatBoost). "
            "P10 represents your conservative 90% confidence cash flow floor, P50 is your expected baseline, and P90 models aggressive market capture.",
            self.styles['BodyCustom']
        ))

        # Extract Overall Forecast rows from predictions_df
        ov_df = predictions_df[predictions_df['dimension_type'] == 'Overall']
        fc_table_data = [[
            Paragraph("Planning Window", self.styles['TableHeader']),
            Paragraph("Business Metric", self.styles['TableHeader']),
            Paragraph("P10 (Worst Case)", self.styles['TableHeader']),
            Paragraph("P50 (Expected Case)", self.styles['TableHeader']),
            Paragraph("P90 (Best Case)", self.styles['TableHeader'])
        ]]

        for idx, row in ov_df.iterrows():
            metric = str(row['metric'])
            win = str(row['forecast_period']).replace("_", " ").title()
            
            p10_str = f"${row['p10']:,.0f}" if metric == "Revenue" else f"{row['p10']:.2f}x"
            p50_str = f"${row['p50']:,.0f}" if metric == "Revenue" else f"{row['p50']:.2f}x"
            p90_str = f"${row['p90']:,.0f}" if metric == "Revenue" else f"{row['p90']:.2f}x"

            fc_table_data.append([
                Paragraph(win, self.styles['TableCell']),
                Paragraph(f"<b>{metric}</b>", self.styles['TableCell']),
                Paragraph(p10_str, self.styles['TableCell']),
                Paragraph(f"<b>{p50_str}</b>", self.styles['TableCell']),
                Paragraph(p90_str, self.styles['TableCell'])
            ])

        t_fc = Table(fc_table_data, colWidths=[1.5*inch, 1.2*inch, 1.25*inch, 1.3*inch, 1.25*inch])
        t_fc.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), self.c_slate),
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('GRID', (0,0), (-1,-1), 0.5, self.c_border),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, self.c_light]),
            ('PADDING', (0,0), (-1,-1), 7),
        ]))
        story.append(t_fc)
        story.append(Spacer(1, 20))

        # ==========================================
        # 4. CHANNEL BREAKDOWN & ATTRIBUTION
        # ==========================================
        story.append(Paragraph("3. Channel Performance & Contribution Breakdown", self.styles['SectionHeading']))
        story.append(Paragraph(
            "Treating existing channel attribution as the overarching source of truth, here is the forward 60-day expected "
            "contribution and efficiency analysis across your primary paid acquisition channels.",
            self.styles['BodyCustom']
        ))

        ch_df = predictions_df[(predictions_df['dimension_type'] == 'Channel') & (predictions_df['forecast_period'] == '60_days')]
        ch_table_data = [[
            Paragraph("Acquisition Channel", self.styles['TableHeader']),
            Paragraph("Modeled Metric", self.styles['TableHeader']),
            Paragraph("Conservative (P10)", self.styles['TableHeader']),
            Paragraph("Expected Baseline (P50)", self.styles['TableHeader']),
            Paragraph("Aggressive Scale (P90)", self.styles['TableHeader'])
        ]]

        for idx, row in ch_df.iterrows():
            ch_name = str(row['dimension_value'])
            metric = str(row['metric'])
            p10_str = f"${row['p10']:,.0f}" if metric == "Revenue" else f"{row['p10']:.2f}x"
            p50_str = f"${row['p50']:,.0f}" if metric == "Revenue" else f"{row['p50']:.2f}x"
            p90_str = f"${row['p90']:,.0f}" if metric == "Revenue" else f"{row['p90']:.2f}x"

            ch_table_data.append([
                Paragraph(f"<b>{ch_name}</b>", self.styles['TableCellLeft']),
                Paragraph(metric, self.styles['TableCell']),
                Paragraph(p10_str, self.styles['TableCell']),
                Paragraph(f"<b>{p50_str}</b>", self.styles['TableCell']),
                Paragraph(p90_str, self.styles['TableCell'])
            ])

        t_ch = Table(ch_table_data, colWidths=[1.8*inch, 1.1*inch, 1.2*inch, 1.2*inch, 1.2*inch])
        t_ch.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), self.c_teal),
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('GRID', (0,0), (-1,-1), 0.5, self.c_border),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, self.c_light]),
            ('PADDING', (0,0), (-1,-1), 6),
        ]))
        story.append(t_ch)
        story.append(Spacer(1, 20))

        # Page Break to keep sections beautifully structured
        story.append(PageBreak())

        # ==========================================
        # 5. OPTUNA BUDGET OPTIMIZER RECOMMENDATIONS
        # ==========================================
        story.append(Paragraph("4. Optuna Enterprise Budget Optimizer", self.styles['SectionHeading']))
        story.append(Paragraph(
            f"Using Optuna automated hyperparameter & budget search, we optimized a global monthly budget of "
            f"<b>${opt_results.get('max_budget', 100000):,.0f}</b> to maximize total revenue subject to a Target ROAS floor of "
            f"<b>{opt_results.get('target_roas', 4.5)}x</b>. Diminishing returns parameters were calibrated from historical efficiency.",
            self.styles['BodyCustom']
        ))

        rec_ch = opt_results.get("channel_recommendations", {})
        opt_table_data = [[
            Paragraph("Marketing Platform", self.styles['TableHeader']),
            Paragraph("Recommended Spend", self.styles['TableHeader']),
            Paragraph("Expected Revenue Capture", self.styles['TableHeader']),
            Paragraph("Modeled Platform ROAS", self.styles['TableHeader']),
            Paragraph("Target Spend Share", self.styles['TableHeader'])
        ]]

        for ch, data in rec_ch.items():
            sp = data["allocated_spend"]
            rev = data["expected_revenue"]
            roas = data["expected_roas"]
            share = data["budget_share"]

            opt_table_data.append([
                Paragraph(f"<b>{ch}</b>", self.styles['TableCellLeft']),
                Paragraph(f"${sp:,.0f}", self.styles['TableCell']),
                Paragraph(f"${rev:,.0f}", self.styles['TableCell']),
                Paragraph(f"<b>{roas:.2f}x</b>", self.styles['TableCell']),
                Paragraph(f"{share:.1f}%", self.styles['TableCell'])
            ])

        # Overall summary row
        tot_sp = opt_results.get("recommended_total_spend", 100000)
        tot_rev = opt_results.get("expected_total_revenue", 556751)
        tot_roas = opt_results.get("expected_total_roas", 5.57)
        opt_table_data.append([
            Paragraph("<b>GLOBAL OPTIMIZED TOTAL</b>", self.styles['TableCellLeft']),
            Paragraph(f"<b>${tot_sp:,.0f}</b>", self.styles['TableCell']),
            Paragraph(f"<b>${tot_rev:,.0f}</b>", self.styles['TableCell']),
            Paragraph(f"<b>{tot_roas:.2f}x</b>", self.styles['TableCell']),
            Paragraph("<b>100.0%</b>", self.styles['TableCell'])
        ])

        t_opt = Table(opt_table_data, colWidths=[1.8*inch, 1.2*inch, 1.3*inch, 1.1*inch, 1.1*inch])
        t_opt.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), self.c_secondary),
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('GRID', (0,0), (-1,-1), 0.5, self.c_border),
            ('ROWBACKGROUNDS', (0,1), (-1,-2), [colors.white, self.c_light]),
            ('BACKGROUND', (0,-1), (-1,-1), colors.HexColor("#E2E8F0")),
            ('PADDING', (0,0), (-1,-1), 7),
        ]))
        story.append(t_opt)
        story.append(Spacer(1, 20))

        # ==========================================
        # 6. RISK INTELLIGENCE & ACTIONABLE RECOMMENDATIONS
        # ==========================================
        story.append(KeepTogether([
            Paragraph("5. Enterprise Risk Intelligence & Growth Action Plan", self.styles['SectionHeading']),
            Paragraph(
                f"The overarching portfolio Risk Classification is evaluated as <b>{risk_profile.get('risk_classification', 'Medium Risk')}</b> "
                f"(Enterprise Risk Score: {risk_profile.get('risk_score', 45.0)}/100). Below are the specific operational risks "
                "identified by our offline causal intelligence layer and recommended mitigation actions.",
                self.styles['BodyCustom']
            )
        ]))

        factors = risk_profile.get("risk_factors", [])
        risk_table_data = [[
            Paragraph("Evaluated Risk Vector", self.styles['TableHeader']),
            Paragraph("Risk Sub-Score", self.styles['TableHeader']),
            Paragraph("Status", self.styles['TableHeader']),
            Paragraph("Strategic Mitigation Action Plan", self.styles['TableHeader'])
        ]]

        for f in factors:
            status_color = "green" if f["status"] in ["Healthy", "Excellent", "Diversified", "Stable"] else ("red" if f["status"] in ["Action Required", "Volatile", "Concentrated"] else "orange")
            risk_table_data.append([
                Paragraph(f"<b>{f['name']}</b>", self.styles['TableCellLeft']),
                Paragraph(f"{f['score']}/100", self.styles['TableCell']),
                Paragraph(f"<font color='{status_color}'><b>{f['status']}</b></font>", self.styles['TableCell']),
                Paragraph(f['mitigation'], self.styles['TableCellLeft'])
            ])

        t_risk = Table(risk_table_data, colWidths=[1.5*inch, 1.0*inch, 1.0*inch, 3.0*inch])
        t_risk.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), self.c_primary),
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ('GRID', (0,0), (-1,-1), 0.5, self.c_border),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, self.c_light]),
            ('PADDING', (0,0), (-1,-1), 7),
        ]))
        story.append(t_risk)
        story.append(Spacer(1, 25))

        # Sign-off block
        # BUG 13 fix: previously hardcoded a fabricated credential claim ("Team Principal Data
        # Scientist, Staff ML Engineer, Senior Backend, Senior Frontend, and AWS Solutions
        # Architect") into every downloaded PDF — an active false statement in a user-facing
        # deliverable, not a placeholder. Replaced with an honest student-team sign-off,
        # consistent with the BUG 23/24 fix already applied to the live dashboard.
        story.append(KeepTogether([
            HRFlowable(width="100%", thickness=1, color=self.c_border, spaceBefore=10, spaceAfter=10),
            Paragraph("<b>ForecastIQ Revenue Intelligence Architecture</b> — Built for the NetElixir AIgnition 2026 Hackathon Challenge.", self.styles['BodyCustom']),
            Paragraph("<i>Engineered by Pavan &amp; Rohindth, Dayananda Sagar University.</i>", self.styles['BodyCustom'])
        ]))

        # Build Document
        doc.build(story, canvasmaker=NumberedCanvas)
        logger.info(f"Professional Enterprise PDF Report successfully exported to {self.output_path}")
        return self.output_path
